spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog
    username: catalog
    password: catalog
  jpa:
    open-in-view: false
  liquibase:
    contexts: production
  kafka:
    listener:
      auto-startup: false

logging:
  level:
    org.jooq: WARN
    org.testcontainers: INFO
